basePath: /
consumes:
- application/json
definitions:
  Product:
    description: Product defines the structure for an API product
    properties:
      description:
        description: the description of the product
        type: string
        x-go-name: Description
      id:
        description: the id for the product
        format: int64
        minimum: 1
        type: integer
        x-go-name: ID
      name:
        description: the name of the product
        type: string
        x-go-name: Name
      price:
        description: the price of the product
        format: float
        type: number
        x-go-name: Price
      sku:
        description: the SKU of the product
        example: abcd-kmdfg-ercg
        type: string
        x-go-name: SKU
    required:
    - id
    - name
    - price
    - sku
    type: object
    x-go-package: _/home/amit/personal_data/workspace/golang-nickjackson/product-api/data
  Products:
    description: Products is a collection of Product
    items:
      $ref: '#/definitions/Product'
    type: array
    x-go-package: _/home/amit/personal_data/workspace/golang-nickjackson/product-api/data
info:
  description: Documentation for Product API
  title: of Product API
  version: 1.0.0
paths:
  /products:
    get:
      description: Returns a list of products
      operationId: listProducts
      responses:
        "200":
          $ref: '#/responses/productsResponse'
      tags:
      - products
  /products/{id}:
    delete:
      description: Delete's a product from the database
      operationId: deleteProduct
      parameters:
      - description: The id of the product to delete from database.
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "201":
          $ref: '#/responses/noContentResponse'
      tags:
      - products
produces:
- application/json
responses:
  noContentResponse: {}
  productsResponse:
    description: A list of Products returns in the response
    schema:
      items:
        $ref: '#/definitions/Products'
      type: array
schemes:
- http
swagger: "2.0"
